### ISSUE TITLE
Consider audit log to document data transformations

### ISSUE THREAD

**Issue by danyx23** [DouglasConnect/opentox-toxcast#5]
I was thinking about including a new field in every of our data api responses called "auditTrail" or something like this. It would be an array of json objects that would at a minimum contain a timestamp executed and a human readable description, but ideally also things like git changeset hash of the version used etc.

For ToxRefDB e.g. this would in my mind have four entries:
```yaml
auditTrail:
  # Timestamp of the query to the api
  - description: "toxRefApi data retrieval GET operation at /compounds endpoint"
    timestamp: "2017-03-03T05:56:56Z"

  # Information about the API version running on the server
  - description: "Douglas Connect toxRef data API"
    timestamp: "2017-01-01T02:00:00Z"
    git-changeset: "bc3a7362330175491ed87c03c0cbff70dcc6b9e9"
    git-origin: "https://github.com/DouglasConnect/opentox-toxrefdb"

  # Information on the URL the data was downloaded from. timestamp is the date the download was done, release-date is the date the upstream data was made available
  - description: "Download and ingesting of EPA ToxRefDB release"
    url: "ftp://newftp.epa.gov/comptox/High_Throughput_Screening_Data/Animal_Tox_Data/toxrefdb%20(1).zip"
    timestamp: "2017-01-20T05:00:00Z"
    release-date: "2015-05-13T00:00:00Z"

  # Information on the database loader code that transformed that data from CSV into (in this case) Elasticsearch (timestamp is build date)
  - description: "Douglas Connect toxRefDB data importer"
    timestamp: "2017-01-01T02:00:00Z"
    git-changeset: "c5925e150fa62de85f14b3e5cc228e5081b0ffae"
    git-origin: "https://github.com/DouglasConnect/opentox-toxrefdb"
```

**Comment by danyx23** [comment]
The timestamp of the retrieval of the data should also include the exact query used, e.g. 
```yaml
auditTrail:
    - description: "GET operation ..."
      timestamp: "2017-03-03T05:56:56Z"
      url: "https://toxrefdb-api.cloud.douglasconnect.com/beta/compounds?query=Methyl&limit=10"
```
